version: '2'
services:
  node-server:
    image: node:6-slim
    container_name: node-server
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    networks:
      mean-network:
    working_dir: /app
    command: npm run start

  mongo:
    image: mongo
    build: ./
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      mean-network:

volumes:
  mongo-data:
    driver: local

networks:
  mean-network:
